Added mayhem integration
mayhemheroes/unicode-segmentation pull request #1
Opened 2022-05-26 00:30 UTC by harshavamsi

Added dockerfile, mayhem file, github actions to integrate mayhem.

2022-07-24 02:55 UTC, xansec requested changes
Please make the requested changes.

2022-07-24 02:55 UTC, xansec commented on fuzz_target_1.mayhemfile
> +project: unicode-segmentation
Can we rename the fuzz target to something more indicative of what's being fuzzed?

2022-07-25 00:59 UTC, harshavamsi commented
@xansec Changed the target name as you requested.

2022-07-25 19:06 UTC, xansec approved these changes
LGTM!

2022-07-25 19:06 UTC, xansec commented on split_word_bounds.mayhemfile
> +project: unicode-segmentation
I actually was referring to renaming the fuzz target itself. This is fine for now, but check your other submissions and see if you can't rename these.

2022-07-25 19:06 UTC, merged